#!/usr/bin/env python3
"""Generates the app's line icons (Feather-style, 24x24, 2px stroke) as Android vector drawables.

Run from the repository root: python3 tools/generate_icons.py [preview.html]
"""
import os
import sys

ICONS = {
    "search": "M3,11a8,8 0 1,0 16,0a8,8 0 1,0 -16,0M21,21L16.65,16.65",
    "settings": "M4,21V14M4,10V3M12,21V12M12,8V3M20,21V16M20,12V3M1,14H7M9,8H15M17,16H23",
    "refresh": "M23,4V10H17M20.49,15A9,9 0 1,1 18.37,5.64L23,10",
    "back": "M19,12H5M12,19L5,12L12,5",
    "navigation": "M3,11L22,2L13,21L11,13Z",
    "more": "M11,12a1,1 0 1,0 2,0a1,1 0 1,0 -2,0M11,5a1,1 0 1,0 2,0a1,1 0 1,0 -2,0M11,19a1,1 0 1,0 2,0a1,1 0 1,0 -2,0",
    "check": "M20,6L9,17L4,12",
    "close": "M18,6L6,18M6,6L18,18",
    "bell": "M18,8A6,6 0 0,0 6,8c0,7 -3,9 -3,9h18s-3,-2 -3,-9M13.73,21a2,2 0 0,1 -3.46,0",
    "umbrella": "M23,12a11.05,11.05 0 0,0 -22,0zM18,19a3,3 0 0,1 -6,0v-7",
    "droplet": "M12,2.69l5.66,5.66a8,8 0 1,1 -11.31,0z",
    "wind": "M9.59,4.59A2,2 0 1,1 11,8H2M12.59,19.41A2,2 0 1,0 14,16H2M17.73,7.73A2.5,2.5 0 1,1 19.5,12H2",
    "thermometer": "M14,14.76V3.5a2.5,2.5 0 0,0 -5,0v11.26a4.5,4.5 0 1,0 5,0z",
    "eye": "M1,12s4,-8 11,-8s11,8 11,8s-4,8 -11,8s-11,-8 -11,-8zM9,12a3,3 0 1,0 6,0a3,3 0 1,0 -6,0",
    "sun": "M7,12a5,5 0 1,0 10,0a5,5 0 1,0 -10,0M12,1V3M12,21V23M4.22,4.22L5.64,5.64M18.36,18.36L19.78,19.78"
           "M1,12H3M21,12H23M4.22,19.78L5.64,18.36M18.36,5.64L19.78,4.22",
    "sunrise": "M17,18a5,5 0 0,0 -10,0M12,2V9M4.22,10.22L5.64,11.64M1,18H3M21,18H23M18.36,11.64L19.78,10.22"
               "M23,22H1M8,6L12,2L16,6",
    "pin": "M21,10c0,7 -9,13 -9,13s-9,-6 -9,-13a9,9 0 0,1 18,0zM9,10a3,3 0 1,0 6,0a3,3 0 1,0 -6,0",
    "trash": "M3,6H21M19,6V20a2,2 0 0,1 -2,2H7a2,2 0 0,1 -2,-2V6M8,6V4a2,2 0 0,1 2,-2h4a2,2 0 0,1 2,2v2",
    "alert": "M10.29,3.86L1.82,18a2,2 0 0,0 1.71,3h16.94a2,2 0 0,0 1.71,-3L13.71,3.86a2,2 0 0,0 -3.42,0z"
             "M12,9V13M12,17H12.01",
    "shield": "M12,22s8,-4 8,-10V5l-8,-3l-8,3v7c0,6 8,10 8,10z",
    "check_circle": "M22,11.08V12a10,10 0 1,1 -5.93,-9.14M22,4L12,14.01L9,11.01",
    "chevron_down": "M6,9L12,15L18,9",
    "chevron_up": "M18,15L12,9L6,15",
    "clock": "M2,12a10,10 0 1,0 20,0a10,10 0 1,0 -20,0M12,6V12L16,14",
    "calendar": "M5,4H19a2,2 0 0,1 2,2V20a2,2 0 0,1 -2,2H5a2,2 0 0,1 -2,-2V6a2,2 0 0,1 2,-2zM16,2V6M8,2V6M3,10H21",
    "info": "M2,12a10,10 0 1,0 20,0a10,10 0 1,0 -20,0M12,16V12M12,8H12.01",
    "gauge": "M5.07,17A8,8 0 1,1 18.93,17M12,13L15.5,8.5",
    "briefcase": "M4,7H20a2,2 0 0,1 2,2V19a2,2 0 0,1 -2,2H4a2,2 0 0,1 -2,-2V9a2,2 0 0,1 2,-2z"
                 "M16,21V5a2,2 0 0,0 -2,-2h-4a2,2 0 0,0 -2,2v16",
    "snowflake": "M12,2V22M3.34,7L20.66,17M3.34,17L20.66,7M9,4L12,6L15,4M9,20L12,18L15,20",
    "zap": "M13,2L3,14H12L11,22L21,10H12L13,2Z",
    "shirt": "M20.38,3.46L16,2a4,4 0 0,1 -8,0L3.62,3.46a2,2 0 0,0 -1.34,2.23l0.58,3.47a1,1 0 0,0 0.99,0.84H6v10"
             "c0,1.1 0.9,2 2,2h8a2,2 0 0,0 2,-2V10h2.15a1,1 0 0,0 0.99,-0.84l0.58,-3.47a2,2 0 0,0 -1.34,-2.23z",
    "glasses": "M2,15a4,4 0 1,0 8,0a4,4 0 1,0 -8,0M14,15a4,4 0 1,0 8,0a4,4 0 1,0 -8,0M10,15a2,2 0 0,1 4,0"
               "M2.5,13L5,7c0.7,-1.3 1.4,-2 3,-2M21.5,13L19,7c-0.7,-1.3 -1.5,-2 -3,-2",
    "trending_down": "M23,18L13.5,8.5L8.5,13.5L1,6M17,18H23V12",
    "fog": "M4,8H20M2,12H22M6,16H18",
    "arrow_up": "M12,2L19,21L12,17L5,21L12,2Z",
    "crosshair": "M2,12a10,10 0 1,0 20,0a10,10 0 1,0 -20,0M22,12H18M6,12H2M12,6V2M12,22V18",
}

TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/generate_icons.py -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path
        android:fillColor="#00000000"
        android:pathData="{path}"
        android:strokeWidth="2"
        android:strokeColor="#FFFFFFFF"
        android:strokeLineCap="round"
        android:strokeLineJoin="round" />
</vector>
"""

def main():
    out_dir = os.path.join("app", "src", "main", "res", "drawable")
    for name, path in ICONS.items():
        with open(os.path.join(out_dir, f"ic_{name}.xml"), "w") as f:
            f.write(TEMPLATE.format(path=path))
    if len(sys.argv) > 1:
        cells = "".join(
            f'<div style="display:inline-block;width:90px;text-align:center;margin:6px;font:11px sans-serif;color:#ccc">'
            f'<svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" '
            f'stroke-linecap="round" stroke-linejoin="round"><path d="{p}"/></svg><br>{n}</div>'
            for n, p in ICONS.items()
        )
        with open(sys.argv[1], "w") as f:
            f.write(f'<html><body style="background:#1C273B;margin:12px">{cells}</body></html>')
    print(f"{len(ICONS)} icons written")

if __name__ == "__main__":
    main()
